In [175]:
import pandas as pd
import matplotlib.pyplot as plt
from pathlib import Path
import numpy as np
import json
import re

In [167]:
polarDataFolder = "data/rawPolarData"
format = "json"
data_fields = ['247ohr', 'account-data', 'account-profile', 'activity', 'generic', 'nightly_recovery', 'nightly_recovery_blob', 'ppi_sample', 'sleep_result', 'sleep_score', 'sleep_wake', 'sport_profiles' ]

activity_files = list(Path(polarDataFolder).glob(f"*activity-2026*.{format}"))
sleep_result_files = list(Path(polarDataFolder).glob(f"*sleep_result*.{format}"))
sleep_score_files = list(Path(polarDataFolder).glob(f"*sleep_score*.{format}"))
sleep_wake_files = list(Path(polarDataFolder).glob(f"*sleep_wake*.{format}"))
sport_profiles_files = list(Path(polarDataFolder).glob(f"*sport_profiles*.{format}"))
nightly_recovery_files = list(Path(polarDataFolder).glob(f"*nightly_recovery*.{format}"))
nightly_recovery_blob_files = list(Path(polarDataFolder).glob(f"*nightly_recovery_blob*.{format}"))
ppi_sample_files = list(Path(polarDataFolder).glob(f"*ppi_sample*.{format}"))
account_data_files = list(Path(polarDataFolder).glob(f"*account-data*.{format}"))
account_profile_files = list(Path(polarDataFolder).glob(f"*account-profile*.{format}"))
generic_files = list(Path(polarDataFolder).glob(f"*generic*.{format}"))
ohr_files = list(Path(polarDataFolder).glob(f"*247ohr*.{format}"))

In [ ]:
data['summary']
step_count = data['summary']['stepsDistance']
step_distance = data['summary']['stepsDistance']
calories = data['summary']['calories']
sleep_quality = data['summary']['sleepQuality']
sleepDuration = data['summary']['sleepDuration']

{'startTime': '00:00:00.000',
 'endTime': '23:59:59.000',
 'stepCount': 6192,
 'stepsDistance': 3204.314453125,
 'calories': 2578,
 'sleepQuality': 0.792453,
 'sleepDuration': 'PT12720S',
 'inactivityAlertCount': 0,
 'dailyMetMinutes': 176.40937500000058,
 'activityLevels': [{'level': 'NO_DATA', 'duration': 'PT0S'},
  {'level': 'SLEEP', 'duration': 'PT23430S'},
  {'level': 'SEDENTARY', 'duration': 'PT29280S'},
  {'level': 'LIGHT', 'duration': 'PT31290S'},
  {'level': 'CONTINUOS_MODERATE', 'duration': 'PT2400S'},
  {'level': 'INTERMITTENT_MODERATE', 'duration': 'PT0S'},
  {'level': 'CONTINUOS_VIGOROUS', 'duration': 'PT0S'},
  {'level': 'INTERMITTENT_VIGOROUS', 'duration': 'PT0S'},
  {'level': 'NON_WEAR', 'duration': 'PT0S'}]}

In [ ]:
final_df = pd.DataFrame()

for file in activity_files:
    with open(file) as f:
        data = json.load(f)

    try:
        data['summary']
    except KeyError:
        continue
    date_str = re.search(r'\d{4}-\d{2}-\d{2}', str(file)).group()

    data['summary']
    step_count = data['summary']['stepsDistance']
    step_distance = data['summary']['stepsDistance']
    calories = data['summary']['calories']
    sleep_quality = data['summary']['sleepQuality']
    sleepDuration = data['summary']['sleepDuration']

    df = pd.DataFrame({
        'date': [date_str],
        'step_count': [step_count],
        'step_distance': [step_distance],
        'calories': [calories],
        'sleep_quality': [sleep_quality],
        'sleepDuration': [sleepDuration]

    })
    df['date'] = pd.to_datetime(df['date'])

    final_df = pd.concat([final_df, df], ignore_index=True)
    final_df['date'] = pd.to_datetime(final_df['date'])


final_df = final_df.sort_values(by='date').reset_index(drop=True)
final_df

,date,step_count,step_distance,calories,sleep_quality,sleepDuration
0,2026-08-20,4868.448242,4868.448242,2162,0.000000,PT0S
1,2026-08-21,7300.249512,7300.249512,2602,0.836676,PT10470S
2,2026-08-22,11364.366211,11364.366211,2609,0.723790,PT14880S
3,2026-08-23,17841.220703,17841.220703,3035,0.761803,PT13980S
4,2026-08-24,6413.073242,6413.073242,2718,0.744615,PT9750S
5,2026-08-25,5003.375488,5003.375488,2558,0.762523,PT16170S
6,2026-08-26,6121.125488,6121.125488,2656,0.790251,PT20310S
7,2026-08-27,4793.776855,4793.776855,2483,0.717815,PT23070S
8,2026-08-28,8376.846680,8376.846680,2804,0.809365,PT8970S
9,2026-08-29,4385.196289,4385.196289,2451,0.785156,PT7680S
10,2026-08-30,149.309708,149.309708,746,0.760766,PT25080S
11,2026-09-06,1969.688721,1969.688721,2243,0.000000,PT0S
12,2026-09-07,2544.833740,2544.833740,2278,0.728671,PT21450S
13,2026-09-08,6098.256836,6098.256836,2555,0.000000,PT0S
14,2026-09-09,3697.020020,3697.020020,2195,0.708603,PT32430S
15,2026-09-10,3098.872803,3098.872803,2135,0.717636,PT31980S
16,2026-09-11,3718.093994,3718.093994,2326,0.708122,PT11820S
17,2026-09-12,553.215393,553.215393,1717,0.685969,PT13470S
18,2026-09-13,9714.746094,9714.746094,2643,0.723340,PT29820S
19,2026-09-14,8475.139648,8475.139648,2483,0.753571,PT8400S
20,2026-09-15,3215.659180,3215.659180,2221,0.804708,PT34410S
21,2026-09-16,1391.616943,1391.616943,2086,0.719595,PT17760S
22,2026-09-17,7129.833496,7129.833496,2570,0.751543,PT19440S
23,2026-09-18,2952.554199,2952.554199,2308,0.791237,PT11640S
24,2026-09-19,6522.142578,6522.142578,2500,0.718078,PT23730S
25,2026-09-20,2377.379150,2377.379150,2188,0.782222,PT27000S
26,2026-09-21,8257.235352,8257.235352,2733,0.746495,PT25680S
27,2026-09-22,9352.808594,9352.808594,2588,0.762972,PT25440S
28,2026-09-23,8011.273926,8011.273926,2636,0.777648,PT25770S
29,2026-09-24,6292.457031,6292.457031,2498,0.774699,PT24900S
30,2026-09-25,7623.626465,7623.626465,2669,0.770964,PT23970S
31,2026-09-26,5071.503418,5071.503418,2559,0.766289,PT21180S
32,2026-09-27,5818.709961,5818.709961,2509,0.768786,PT15570S
33,2026-09-28,3984.174561,3984.174561,2416,0.785714,PT19320S
34,2026-09-29,7014.202637,7014.202637,2729,0.801779,PT23610S
35,2026-09-30,5611.921875,5611.921875,2442,0.765727,PT27660S
36,2026-10-01,5418.727539,5418.727539,2330,0.729805,PT21540S
37,2026-10-02,9881.850586,9881.850586,2598,0.750911,PT24690S
38,2026-10-03,4452.258301,4452.258301,2521,0.739130,PT10350S
39,2026-10-04,3975.643311,3975.643311,2481,0.806452,PT13020S
40,2026-10-05,3204.314453,3204.314453,2578,0.792453,PT12720S
41,2026-10-06,5771.035156,5771.035156,2691,0.759336,PT14460S
42,2026-10-07,6955.742676,6955.742676,2476,0.757539,PT24870S
43,2026-10-08,8471.480469,8471.480469,2610,0.770068,PT22050S
44,2026-10-09,8392.161133,8392.161133,2628,0.692525,PT21270S
45,2026-10-10,4718.202637,4718.202637,2468,0.672886,PT24120S
46,2026-10-11,4748.846680,4748.846680,2475,0.000000,PT0S
47,2026-10-12,4446.333496,4446.333496,2332,0.818381,PT27420S
48,2026-10-13,4934.535645,4934.535645,2479,0.682310,PT16620S
49,2026-10-14,6122.871094,6122.871094,2427,0.706549,PT23820S
50,2026-10-15,10127.068359,10127.068359,2736,0.746528,PT25920S
51,2026-10-16,5136.310547,5136.310547,2290,0.710526,PT22800S
52,2026-10-17,4955.571777,4955.571777,2464,0.752890,PT20760S
53,2026-10-18,3821.533936,3821.533936,2406,0.846821,PT20760S
54,2026-10-19,1043.211792,1043.211792,1138,0.756359,PT22410S

In [166]:
df = pd.DataFrame({
    'mets': data['samples']['mets'],
    'steps': np.repeat(data['samples']['steps'], 2),
    'date': data['date']
})

df['mets'] = df['mets'].str['value']
df['steps'] = df['steps'].str['value']

In [ ]:
activity_data = [pd.read_json(file) for file in activity_files]
activity_data = pd.concat(activity_data, ignore_index=True)
date = activity_data["date"].unique()

all_records = []

for sample_name, sample_values in data.get("samples", {}).items():
    for item in sample_values:
        all_records.append({
            "date": date,
            # "sample_name": sample_name,
            # "localTime": item.get("localTime"),
            # "value": item.get("value"),
        })

activity_data = pd.DataFrame(all_records)
activity_data

                                                   date sample_name
0     [2026-09-02 00:00:00, 2026-08-22 00:00:00, 202...        mets
1     [2026-09-02 00:00:00, 2026-08-22 00:00:00, 202...        mets
2     [2026-09-02 00:00:00, 2026-08-22 00:00:00, 202...        mets
3     [2026-09-02 00:00:00, 2026-08-22 00:00:00, 202...        mets
4     [2026-09-02 00:00:00, 2026-08-22 00:00:00, 202...        mets
...                                                 ...         ...
4316  [2026-09-02 00:00:00, 2026-08-22 00:00:00, 202...       steps
4317  [2026-09-02 00:00:00, 2026-08-22 00:00:00, 202...       steps
4318  [2026-09-02 00:00:00, 2026-08-22 00:00:00, 202...       steps
4319  [2026-09-02 00:00:00, 2026-08-22 00:00:00, 202...       steps
4320  [2026-09-02 00:00:00, 2026-08-22 00:00:00, 202...  metSources

[4321 rows x 2 columns]

In [131]:
import glob
import json
import pandas as pd

all_records = []

for file_path in activity_files:
    with open(file_path) as f:
        data = json.load(f)

    date = data.get("date")

    for sample_name, sample_values in data.get("samples", {}).items():
        for item in sample_values:
            all_records.append({
                "date": date,
                "sample_name": sample_name,
                "localTime": item.get("localTime"),
                "value": item.get("value"),
            })

activity_data = pd.DataFrame(all_records)

AttributeError: 'str' object has no attribute 'get'

In [129]:
activity_data = [pd.read_json(file) for file in activity_files]
activity_data = pd.concat(activity_data, ignore_index=True)
activity_data.samples.notnull()
activity_data

,exportVersion,date,samples,physicalInformation,summary
0,2.7,2026-09-02,"[{'value': 1.125}, {'value': 1.375}, {'value':...",NaN,NaN
1,2.7,2026-09-02,"[{'value': 0}, {'value': 0}, {'value': 6}, {'v...",NaN,NaN
2,2.7,2026-09-02,[1A581F3F],NaN,NaN
3,2.7,2026-09-02,NaN,MALE,NaN
4,2.7,2026-09-02,NaN,1990-11-19,NaN
...,...,...,...,...,...
1040,2.7,2026-08-28,NaN,MALE,NaN
1041,2.7,2026-08-28,NaN,1990-11-19,NaN
1042,2.7,2026-08-28,NaN,175.0,NaN
1043,2.7,2026-08-28,NaN,60.0,NaN
1044,2.7,2026-08-28,NaN,PT28800S,NaN

In [128]:
activity_data = [pd.read_json(file) for file in activity_files]
activity_data = pd.concat(activity_data, ignore_index=True)


date1 = activity_data.date.unique()[0]
print(activity_data.date.unique())

<DatetimeArray>
['2026-09-02 00:00:00', '2026-08-22 00:00:00', '2026-10-16 00:00:00',
 '2026-10-14 00:00:00', '2026-10-01 00:00:00', '2026-09-17 00:00:00',
 '2026-09-05 00:00:00', '2026-10-15 00:00:00', '2026-08-25 00:00:00',
 '2026-10-02 00:00:00', '2026-10-12 00:00:00', '2026-10-07 00:00:00',
 '2026-09-25 00:00:00', '2026-09-13 00:00:00', '2026-10-18 00:00:00',
 '2026-09-04 00:00:00', '2026-09-01 00:00:00', '2026-09-06 00:00:00',
 '2026-10-05 00:00:00', '2026-08-27 00:00:00', '2026-08-21 00:00:00',
 '2026-10-13 00:00:00', '2026-09-27 00:00:00', '2026-09-30 00:00:00',
 '2026-09-03 00:00:00', '2026-09-11 00:00:00', '2026-09-08 00:00:00',
 '2026-10-19 00:00:00', '2026-09-21 00:00:00', '2026-09-16 00:00:00',
 '2026-09-29 00:00:00', '2026-09-19 00:00:00', '2026-09-24 00:00:00',
 '2026-09-07 00:00:00', '2026-10-09 00:00:00', '2026-10-04 00:00:00',
 '2026-09-18 00:00:00', '2026-10-11 00:00:00', '2026-10-08 00:00:00',
 '2026-10-10 00:00:00', '2026-08-23 00:00:00', '2026-08-20 00:00:00',
 '2026-08-30 00:00:00', '2026-09-22 00:00:00', '2026-09-20 00:00:00',
 '2026-09-23 00:00:00', '2026-09-09 00:00:00', '2026-08-24 00:00:00',
 '2026-10-06 00:00:00', '2026-08-31 00:00:00', '2026-10-03 00:00:00',
 '2026-09-15 00:00:00', '2026-09-26 00:00:00', '2026-08-26 00:00:00',
 '2026-09-28 00:00:00', '2026-09-12 00:00:00', '2023-01-01 00:00:00',
 '2026-09-10 00:00:00', '2026-09-14 00:00:00', '2026-10-17 00:00:00',
 '2026-08-29 00:00:00', '2026-08-28 00:00:00']
Length: 62, dtype: datetime64[us]

In [112]:
activities_dict = {} 

for date1 in activity_data.date.unique():
    try:
        vals = activity_data.loc[activity_data['date']==date1].iloc[0]['samples']
        vals_values = [item['value'] for item in vals]
        activities_dict[date1] = vals_values
        # print(activities_dict)
    except Exception as e:
        pass
        # print(f"Error processing date {date1}: {e}")

# sort by date
activities_dict = dict(sorted(activities_dict.items()))
activities_dict.keys()

dict_keys([Timestamp('2023-01-01 00:00:00'), Timestamp('2026-08-31 00:00:00'), Timestamp('2026-09-01 00:00:00'), Timestamp('2026-09-02 00:00:00'), Timestamp('2026-09-03 00:00:00'), Timestamp('2026-09-04 00:00:00'), Timestamp('2026-09-05 00:00:00')])

In [121]:
list(activities_dict.keys())

[Timestamp('2023-01-01 00:00:00'),
 Timestamp('2026-08-31 00:00:00'),
 Timestamp('2026-09-01 00:00:00'),
 Timestamp('2026-09-02 00:00:00'),
 Timestamp('2026-09-03 00:00:00'),
 Timestamp('2026-09-04 00:00:00'),
 Timestamp('2026-09-05 00:00:00')]

In [87]:
vals1[9].values()

#dict_values to float
vals1_float = [float(value) for value in vals1[9].values()]
vals1_float[0]

1.25

In [ ]:
date1 = activity_data.date.unique()[0]
vals1 = activity_data.loc[activity_data['date']==date1].iloc[0]['samples']

vals_list = []
for sample in vals1:
    vals_list.append(sample.values()[0])

TypeError: 'dict_values' object is not subscriptable

In [44]:
date = activity_data.loc[activity_data['date']=='2026-09-03'].iloc[0]['date']
vals1 = activity_data.loc[activity_data['date']=='2026-09-03'].iloc[0]['samples']
vals1 = [sample for sample in activity_data.loc[activity_data['date']=='2026-09-03'].iloc[0]['samples']]

In [58]:
vals1[0].values()
all_vals = [sample for sample in vals1[0].values()]
all_vals

[1.0]